version: "3"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    user: $UID:$GID
    environment:
      - NODE_ENV=development
    working_dir: /home/node/app
    volumes:
      - ./app/:/home/node/app
    expose:
      - "8081"
    command: "npm start"
